version: '3.8'

services:
  indexer:
    build: .
    image: universal-evm-indexer
    container_name: apechain-indexer
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./run-data:/app/run-data
      - ./config:/app/config
    # Load environment variables from .env file
    env_file:
      - .env
    environment:
      - LOG_LEVEL=info
    # Mount config/run.json to configure the indexer
    # Ensure config/run.json exists locally
